[package]
name = "lofi"
version = "0.2.0"
edition = "2021"

[[bin]]
name = "lofi"
path = "src/main.rs"
required-features = [ "build-binary" ]

[lib]
name = "lofi"
path = "src/lib.rs"

[features]
build-binary = [
    "correlate",
    "filter",

    "clap",
    "csv",
    "geojson",
]
correlate = [
    "tlms/locations",
    "tlms/telegrams",
    "serde_json",
]
filter = [
    "tlms/measurements",
    "tlms/telegrams",
    "serde",
    "serde_json",
]

[dependencies]
tlms = { git = "https://github.com/tlm-solutions/tlms.rs", version = "*", default-features = false }
clap = { version = "4.1", features = ["derive"], optional = true }
csv = { version = "1.1.6", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "*", optional = true }
geojson = { version = "0.24", optional = true }
log = "0.4"
stderrlog = "0.5.3"
