[package]
name = "lofi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0", features = ["derive"] }
csv = "1.1.6"
dump-dvb = { git = "https://github.com/dump-dvb/dump-dvb.rs", version = "0.5" }
overpass-turbo = { git = "https://github.com/revol-xut/overpass-turbo.rs", version = "0.1", features = [ "simple"]}
gpx = "0.8.6"
log = "0.4.7"
stderrlog = "0.5.3"
serde = { version = "1", features = ["derive"] }
serde_json = "*"
chrono = { version = "*", features = ["serde", "rustc-serialize"] }
uuid = "*"
geojson =  "*"
geo-types = "*"
random_color = "0.6"
