[package]
name = "lofi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.20"
clap = { version = "4.0", features = ["derive"] }
csv = "1.1.6"
dump-dvb = { git = "https://github.com/dump-dvb/dump-dvb.rs", version = "0.5" }
geojson = "0.23.0"
gpx = "0.8.6"
serde = "1.0.141"
serde_json = "1.0.83"
